# Generated by Django 2.2.7 on 2020-06-11 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('youtube_link', models.CharField(max_length=600)),
                ('notes2', models.ImageField(blank=True, default='', upload_to='static2/images')),
                ('notes1', models.ImageField(blank=True, default='', upload_to='static2/images')),
                ('notes3', models.ImageField(blank=True, default='', upload_to='static2/images')),
                ('notes4', models.ImageField(blank=True, default='', upload_to='static2/images')),
                ('timeStamp', models.DateTimeField(blank=True)),
                ('categories', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='online_exam.Category')),
            ],
        ),
    ]
