# Generated by Django 2.2 on 2020-07-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_exam', '0003_auto_20200614_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_bank',
            name='image2',
            field=models.ImageField(null='true', upload_to='static2/images'),
            preserve_default='true',
        ),
    ]
