# Generated by Django 2.2 on 2020-07-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_exam', '0004_question_bank_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_bank',
            name='image2',
            field=models.ImageField(blank=True, default='', upload_to='static2/images'),
        ),
    ]
