# Generated by Django 2.2 on 2020-07-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_exam', '0005_auto_20200714_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_bank',
            name='image2',
            field=models.ImageField(null='true', upload_to='static2/images'),
        ),
    ]
