# Generated by Django 2.2 on 2020-07-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_exam', '0006_auto_20200714_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_bank',
            name='image2',
            field=models.ImageField(blank='True', null='true', upload_to=''),
        ),
    ]
